/**
 * CFO Direct Index - Forward Test Dashboard
 * Interactive dashboard with Plotly charts and dynamic data loading
 */

// Portfolio data will be loaded from JSON file generated by Python script
let portfolioData = null;

// Sector color palette
const SECTOR_COLORS = {
    'Technology': '#58a6ff',
    'Healthcare': '#3fb950',
    'Financial Services': '#a371f7',
    'Consumer Cyclical': '#f0883e',
    'Communication Services': '#f85149',
    'Industrials': '#6e7681',
    'Consumer Defensive': '#d29922',
    'Energy': '#238636',
    'Utilities': '#388bfd',
    'Real Estate': '#bf8700',
    'Basic Materials': '#8b949e',
    'Other': '#484f58'
};

// Format currency
function formatCurrency(value) {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(value);
}

// Format percentage
function formatPercent(value, decimals = 2) {
    return (value * 100).toFixed(decimals) + '%';
}

// Format number with commas
function formatNumber(value) {
    return new Intl.NumberFormat('en-US').format(value);
}

// Load portfolio data from JSON file
async function loadPortfolioData() {
    try {
        const response = await fetch('data/portfolio.json');
        if (!response.ok) {
            throw new Error('Failed to load portfolio data');
        }
        portfolioData = await response.json();
        return portfolioData;
    } catch (error) {
        console.error('Error loading portfolio data:', error);
        // Use demo data for preview
        return getDemoData();
    }
}

// Demo data for when real data isn't available
function getDemoData() {
    return {
        lastUpdated: new Date().toISOString(),
        inceptionDate: '2026-01-09',
        portfolioValue: 9950000,
        cashBalance: 99500,
        harvestedLosses: 0,
        positions: 498,
        lots: 498,
        ytdReturn: -0.005,
        dailyReturn: 0,
        dailyChange: 0,
        holdings: [
            { symbol: 'NVDA', value: 667835, weight: 0.0675, pnl: 0 },
            { symbol: 'GOOG', value: 590000, weight: 0.0596, pnl: 0 },
            { symbol: 'GOOGL', value: 589500, weight: 0.0595, pnl: 0 },
            { symbol: 'AAPL', value: 569500, weight: 0.0575, pnl: 0 },
            { symbol: 'MSFT', value: 529600, weight: 0.0535, pnl: 0 },
            { symbol: 'AMZN', value: 393000, weight: 0.0397, pnl: 0 },
            { symbol: 'META', value: 244500, weight: 0.0247, pnl: 0 },
            { symbol: 'AVGO', value: 243500, weight: 0.0246, pnl: 0 },
            { symbol: 'TSLA', value: 219800, weight: 0.0222, pnl: 0 },
            { symbol: 'BRK-B', value: 160400, weight: 0.0162, pnl: 0 }
        ],
        sectors: {
            'Technology': 32.5,
            'Healthcare': 12.8,
            'Financial Services': 13.2,
            'Consumer Cyclical': 10.1,
            'Communication Services': 8.9,
            'Industrials': 8.5,
            'Consumer Defensive': 6.2,
            'Energy': 3.8,
            'Utilities': 2.5,
            'Real Estate': 1.5
        },
        trades: [],
        snapshots: [
            { date: '2026-01-09', value: 9900500, benchmark: 100 }
        ]
    };
}

// Update dashboard with data
function updateDashboard(data) {
    // Header info
    document.getElementById('lastUpdated').textContent = new Date(data.lastUpdated).toLocaleString();

    // Metric cards
    document.getElementById('totalValue').textContent = formatCurrency(data.portfolioValue);

    const dailyChangeEl = document.getElementById('dailyChange');
    const dailyChange = data.dailyChange || 0;
    const dailyPct = data.dailyReturn || 0;
    dailyChangeEl.textContent = `${dailyChange >= 0 ? '+' : ''}${formatCurrency(dailyChange)} (${formatPercent(dailyPct)})`;
    dailyChangeEl.className = `change ${dailyChange >= 0 ? 'up' : 'down'}`;

    const ytdReturnEl = document.getElementById('ytdReturn');
    ytdReturnEl.textContent = formatPercent(data.ytdReturn || 0);
    ytdReturnEl.className = `value mono ${(data.ytdReturn || 0) >= 0 ? 'positive' : 'negative'}`;

    document.getElementById('harvestedLosses').textContent = formatCurrency(data.harvestedLosses || 0);
    document.getElementById('cashBalance').textContent = formatCurrency(data.cashBalance);
    document.getElementById('cashPct').textContent = `${((data.cashBalance / data.portfolioValue) * 100).toFixed(2)}% of portfolio`;

    document.getElementById('numPositions').textContent = data.positions;
    document.getElementById('numLots').textContent = `${data.lots} tax lots`;

    document.getElementById('inceptionDate').textContent = data.inceptionDate;
    const daysDiff = Math.floor((new Date() - new Date(data.inceptionDate)) / (1000 * 60 * 60 * 24));
    document.getElementById('daysActive').textContent = `${daysDiff} days active`;
    document.getElementById('initDate').textContent = data.inceptionDate;

    // Render weight comparison tables
    renderWeightComparison(data.topHoldings || data.holdings);
    renderDriftTable(data.topDrift || data.holdings);
    renderSectorComparison(data.sectorComparison);

    // Render sector bar chart
    renderSectorBarChart(data.sectorComparison);

    // Render performance chart
    renderPerformanceChart(data.snapshots);

    // Render activity feed
    renderActivityFeed(data.trades);
}

// Render top holdings weight comparison vs S&P 500
function renderWeightComparison(holdings) {
    const tbody = document.getElementById('weightComparisonBody');

    if (!holdings || holdings.length === 0) {
        tbody.innerHTML = '<tr><td colspan="4">No data available</td></tr>';
        return;
    }

    tbody.innerHTML = holdings.slice(0, 10).map(h => {
        const drift = h.drift || 0;
        const driftClass = drift >= 0 ? 'positive' : 'negative';
        const driftSign = drift >= 0 ? '+' : '';
        return `
            <tr>
                <td class="symbol">${h.symbol}</td>
                <td>${(h.weight * 100).toFixed(2)}%</td>
                <td class="weight">${((h.benchmarkWeight || 0) * 100).toFixed(2)}%</td>
                <td class="${driftClass}">${driftSign}${(drift * 100).toFixed(2)}%</td>
            </tr>
        `;
    }).join('');
}

// Render top drift positions (largest deviations from S&P)
function renderDriftTable(driftData) {
    const tbody = document.getElementById('driftTableBody');

    if (!driftData || driftData.length === 0) {
        tbody.innerHTML = '<tr><td colspan="4">No data available</td></tr>';
        return;
    }

    tbody.innerHTML = driftData.slice(0, 10).map(h => {
        const drift = h.drift || 0;
        const driftClass = drift >= 0 ? 'positive' : 'negative';
        const driftSign = drift >= 0 ? '+' : '';
        return `
            <tr>
                <td class="symbol">${h.symbol}</td>
                <td>${(h.weight * 100).toFixed(2)}%</td>
                <td class="weight">${((h.benchmarkWeight || 0) * 100).toFixed(2)}%</td>
                <td class="${driftClass}">${driftSign}${(drift * 100).toFixed(2)}%</td>
            </tr>
        `;
    }).join('');
}

// Render sector weight comparison table
function renderSectorComparison(sectorData) {
    const tbody = document.getElementById('sectorComparisonBody');

    if (!sectorData || sectorData.length === 0) {
        tbody.innerHTML = '<tr><td colspan="4">No sector data available</td></tr>';
        return;
    }

    tbody.innerHTML = sectorData.map(s => {
        const drift = s.drift || 0;
        const driftClass = drift >= 0 ? 'positive' : 'negative';
        const driftSign = drift >= 0 ? '+' : '';
        return `
            <tr>
                <td class="symbol">${s.sector}</td>
                <td>${s.portfolioWeight.toFixed(1)}%</td>
                <td class="weight">${s.benchmarkWeight.toFixed(1)}%</td>
                <td class="${driftClass}">${driftSign}${drift.toFixed(1)}%</td>
            </tr>
        `;
    }).join('');
}

// Render sector bar chart comparing portfolio vs S&P
function renderSectorBarChart(sectorData) {
    const container = document.getElementById('sectorBarChart');

    if (!sectorData || sectorData.length === 0) {
        container.innerHTML = '<div class="loading">No sector data available</div>';
        return;
    }

    const sectors = sectorData.slice(0, 10).map(s => s.sector);
    const portfolioWeights = sectorData.slice(0, 10).map(s => s.portfolioWeight);
    const benchmarkWeights = sectorData.slice(0, 10).map(s => s.benchmarkWeight);

    const data = [
        {
            x: portfolioWeights,
            y: sectors,
            type: 'bar',
            orientation: 'h',
            name: 'Portfolio',
            marker: { color: '#58a6ff' }
        },
        {
            x: benchmarkWeights,
            y: sectors,
            type: 'bar',
            orientation: 'h',
            name: 'S&P 500',
            marker: { color: '#6e7681' }
        }
    ];

    const layout = {
        barmode: 'group',
        showlegend: true,
        legend: {
            x: 1,
            y: 1.1,
            orientation: 'h',
            font: { color: '#8b949e' }
        },
        xaxis: {
            title: 'Weight %',
            showgrid: true,
            gridcolor: '#21262d',
            color: '#6e7681',
            tickfont: { color: '#6e7681' }
        },
        yaxis: {
            showgrid: false,
            color: '#6e7681',
            tickfont: { color: '#8b949e', size: 11 },
            automargin: true
        },
        margin: { t: 30, b: 40, l: 120, r: 20 },
        paper_bgcolor: 'transparent',
        plot_bgcolor: 'transparent',
        bargap: 0.3,
        bargroupgap: 0.1
    };

    const config = { displayModeBar: false, responsive: true };

    Plotly.newPlot('sectorBarChart', data, layout, config);
}

// Render holdings table
function renderHoldingsTable(holdings) {
    const tbody = document.getElementById('holdingsTableBody');

    if (!holdings || holdings.length === 0) {
        tbody.innerHTML = '<tr><td colspan="4">No holdings data available</td></tr>';
        return;
    }

    tbody.innerHTML = holdings.slice(0, 15).map(h => {
        const pnlClass = h.pnl >= 0 ? 'positive' : 'negative';
        const pnlSign = h.pnl >= 0 ? '+' : '';
        return `
            <tr>
                <td class="symbol">${h.symbol}</td>
                <td>${formatCurrency(h.value)}</td>
                <td class="weight">${(h.weight * 100).toFixed(2)}%</td>
                <td class="${pnlClass}">${pnlSign}${formatCurrency(h.pnl)}</td>
            </tr>
        `;
    }).join('');
}

// Render sector donut chart
function renderSectorChart(sectors) {
    if (!sectors) return;

    const labels = Object.keys(sectors);
    const values = Object.values(sectors);
    const colors = labels.map(s => SECTOR_COLORS[s] || SECTOR_COLORS['Other']);

    const data = [{
        type: 'pie',
        hole: 0.6,
        labels: labels,
        values: values,
        marker: {
            colors: colors
        },
        textinfo: 'none',
        hovertemplate: '%{label}: %{value:.1f}%<extra></extra>'
    }];

    const layout = {
        showlegend: false,
        margin: { t: 10, b: 10, l: 10, r: 10 },
        paper_bgcolor: 'transparent',
        plot_bgcolor: 'transparent',
        font: { color: '#8b949e' }
    };

    const config = { displayModeBar: false, responsive: true };

    Plotly.newPlot('sectorChart', data, layout, config);

    // Render legend
    const legendEl = document.getElementById('sectorLegend');
    legendEl.innerHTML = labels.slice(0, 8).map((sector, i) => `
        <div class="sector-legend-item">
            <span class="name">
                <span class="dot" style="background: ${colors[i]}"></span>
                ${sector}
            </span>
            <span class="weight">${values[i].toFixed(1)}%</span>
        </div>
    `).join('');
}

// Render performance chart
function renderPerformanceChart(snapshots) {
    if (!snapshots || snapshots.length === 0) {
        document.getElementById('performanceChart').innerHTML = '<div class="loading">No performance data available</div>';
        return;
    }

    const dates = snapshots.map(s => s.date);
    const baseValue = snapshots[0].value;
    const portfolioIndexed = snapshots.map(s => (s.value / baseValue) * 100);
    const benchmarkIndexed = snapshots.map(s => s.benchmark || 100);

    const data = [
        {
            x: dates,
            y: portfolioIndexed,
            type: 'scatter',
            mode: 'lines',
            name: 'Portfolio',
            line: { color: '#58a6ff', width: 2.5 }
        },
        {
            x: dates,
            y: benchmarkIndexed,
            type: 'scatter',
            mode: 'lines',
            name: 'S&P 500',
            line: { color: '#6e7681', width: 1.5, dash: 'dash' }
        }
    ];

    const layout = {
        showlegend: true,
        legend: {
            x: 0,
            y: 1.1,
            orientation: 'h',
            font: { color: '#8b949e' }
        },
        xaxis: {
            showgrid: false,
            color: '#6e7681',
            tickfont: { color: '#6e7681' }
        },
        yaxis: {
            title: 'Indexed Value',
            showgrid: true,
            gridcolor: '#21262d',
            color: '#6e7681',
            tickfont: { color: '#6e7681' }
        },
        margin: { t: 40, b: 40, l: 60, r: 20 },
        paper_bgcolor: 'transparent',
        plot_bgcolor: 'transparent',
        hovermode: 'x unified'
    };

    const config = { displayModeBar: false, responsive: true };

    Plotly.newPlot('performanceChart', data, layout, config);
}

// Render activity feed
function renderActivityFeed(trades) {
    const feed = document.getElementById('activityFeed');

    if (!trades || trades.length === 0) {
        // Keep the default initialization message
        return;
    }

    const recentTrades = trades.slice(-10).reverse();

    feed.innerHTML = recentTrades.map(t => {
        const isBuy = t.side === 'BUY';
        const iconClass = t.reason.includes('TLH') ? 'tlh' : (isBuy ? 'buy' : 'sell');
        const icon = t.reason.includes('TLH') ? '💰' : (isBuy ? '📥' : '📤');

        return `
            <li class="activity-item">
                <div class="activity-icon ${iconClass}">${icon}</div>
                <div class="activity-content">
                    <div class="title">${t.side} ${t.symbol}</div>
                    <div class="details">${t.shares.toFixed(2)} shares @ ${formatCurrency(t.price)} (${t.reason})</div>
                </div>
                <div class="activity-time">${new Date(t.timestamp).toLocaleDateString()}</div>
            </li>
        `;
    }).join('');
}

// Initialize dashboard
async function initDashboard() {
    console.log('Initializing CFO Direct Index Dashboard...');

    const data = await loadPortfolioData();
    updateDashboard(data);

    console.log('Dashboard loaded successfully');
}

// Start when DOM is ready
document.addEventListener('DOMContentLoaded', initDashboard);
